// src/redux/actions/types.js

// Tournament action types
export const FETCH_TOURNAMENTS_REQUEST = 'FETCH_TOURNAMENTS_REQUEST';
export const FETCH_TOURNAMENTS_SUCCESS = 'FETCH_TOURNAMENTS_SUCCESS';
export const FETCH_TOURNAMENTS_FAILURE = 'FETCH_TOURNAMENTS_FAILURE';

export const ADD_TOURNAMENT_REQUEST = 'ADD_TOURNAMENT_REQUEST';
export const ADD_TOURNAMENT_SUCCESS = 'ADD_TOURNAMENT_SUCCESS';
export const ADD_TOURNAMENT_FAILURE = 'ADD_TOURNAMENT_FAILURE';

export const UPDATE_TOURNAMENT_REQUEST = 'UPDATE_TOURNAMENT_REQUEST';
export const UPDATE_TOURNAMENT_SUCCESS = 'UPDATE_TOURNAMENT_SUCCESS';
export const UPDATE_TOURNAMENT_FAILURE = 'UPDATE_TOURNAMENT_FAILURE';

export const DELETE_TOURNAMENT_REQUEST = 'DELETE_TOURNAMENT_REQUEST';
export const DELETE_TOURNAMENT_SUCCESS = 'DELETE_TOURNAMENT_SUCCESS';
export const DELETE_TOURNAMENT_FAILURE = 'DELETE_TOURNAMENT_FAILURE';

// New action types for joining a tournament
export const JOIN_TOURNAMENT_REQUEST = 'JOIN_TOURNAMENT_REQUEST';
export const JOIN_TOURNAMENT_SUCCESS = 'JOIN_TOURNAMENT_SUCCESS';
export const JOIN_TOURNAMENT_FAILURE = 'JOIN_TOURNAMENT_FAILURE';

// Wallet action types
export const FETCH_WALLET_REQUEST = 'FETCH_WALLET_REQUEST';
export const FETCH_WALLET_SUCCESS = 'FETCH_WALLET_SUCCESS';
export const FETCH_WALLET_FAILURE = 'FETCH_WALLET_FAILURE';
export const UPDATE_WALLET_REQUEST = 'UPDATE_WALLET_REQUEST';
export const UPDATE_WALLET_SUCCESS = 'UPDATE_WALLET_SUCCESS';
export const UPDATE_WALLET_FAILURE = 'UPDATE_WALLET_FAILURE';
